export const allTeams = [
    { localName: "Brisbane", teamName: "Broncos" },
    { localName: "Canterbury Bankstown", teamName: "Bulldogs" },
    { localName: "Canberra", teamName: "Raiders" },
    { localName: "Cronulla", teamName: "Sharks" },
    { localName: "Gold Coast", teamName: "Titans" },
    { localName: "Manly Warringah", teamName: "Sea Eagles" },
    { localName: "Melbourne", teamName: "Storm" },
    { localName: "New Zealand", teamName: "Warriors" },
    { localName: "North Queensland", teamName: "Cowboys" },
    { localName: "Newcastle", teamName: "Knights" },
    { localName: "Parramatta", teamName: "Eels" },
    { localName: "Penrith", teamName: "Panthers" },
    { localName: "St George Illawarra", teamName: "Dragons" },
    { localName: "South Sydney", teamName: "Rabbitohs" },
    { localName: "Sydney", teamName: "Roosters" },
    { localName: "Wests", teamName: "Tigers" },
    { localName: "Redcliffe", teamName: "Dolphins" },
];
export const globalData = {
    stadiums:
        [
            {
                id: 1,
                venue: 'Suncorp Stadium',
                state: 'QLD',
                city: 'Brisbane',
                capacity: 53,
                gameIds: []
            },
            {
                id: 2,
                venue: 'AAMI Park',
                state: 'VIC',
                city: 'Melbourne',
                capacity: 30,
                gameIds: []
            },
            {
                id: 3,
                venue: 'Go Media Stadium',
                state: 'NZ',
                city: 'Auckland',
                capacity: 25,
                gameIds: []
            },
            {
                id: 4,
                venue: 'Sharks Stadium',
                state: 'NSW',
                city: 'Sydney',
                capacity: 22,
                gameIds: []
            },
            {
                id: 5,
                venue: '4 Pines Park',
                state: 'NSW',
                city: 'Sydney',
                capacity: 18,
                gameIds: []
            },
            {
                id: 6,
                venue: 'Allianz Stadium',
                state: 'NSW',
                city: 'Sydney',
                capacity: 36,
                gameIds: []
            },
            {
                id: 7,
                venue: 'Leichhardt Oval',
                state: 'NSW',
                city: 'Sydney',
                capacity: 20,
                gameIds: []
            },
            {
                id: 8,
                venue: 'WIN Stadium',
                state: 'NSW',
                city: 'Wollongong',
                capacity: 24,
                gameIds: []
            },
            {
                id: 9,
                venue: 'Carrington Park',
                state: 'NSW',
                city: 'Bathurst',
                capacity: 12,
                gameIds: []
            },
            {
                id: 10,
                venue: 'GIO Stadium',
                state: 'ACT',
                city: 'Canverra',
                capacity: 25,
                gameIds: []
            },
            {
                id: 11,
                venue: 'McDonald Jones Stadium',
                state: 'NSW',
                city: 'Newcastle',
                capacity: 33,
                gameIds: []
            },
            {
                id: 12,
                venue: 'Polytec Stadium',
                state: 'NSW',
                city: 'Gosford',
                capacity: 20,
                gameIds: []
            },
            {
                id: 13,
                venue: 'CommBank Stadium',
                state: 'NSW',
                city: 'Sydney',
                capacity: 30,
                gameIds: []
            },
            {
                id: 14,
                venue: 'Queensland Country Bank Stadium',
                state: 'QLD',
                city: 'Townsville',
                capacity: 25,
                gameIds: []
            },
            {
                id: 15,
                venue: 'Accor Stadium',
                state: 'NSW',
                city: 'Sydney',
                capacity: 84,
                gameIds: []
            },
            {
                id: 16,
                venue: 'Cbus Super Stadium',
                state: 'QLD',
                city: 'Gold Coast',
                capacity: 28,
                gameIds: []
            },
            {
                id: 17,
                venue: 'Kayo Stadium',
                state: 'QLD',
                city: 'Redcliffe',
                capacity: 10,
                gameIds: []
            },
            {
                id: 18,
                venue: 'Jubilee Oval',
                state: 'NSW',
                city: 'Sydney',
                capacity: 21,
                gameIds: []
            },
            {
                id: 19,
                venue: 'Optus Stadium',
                state: 'WA',
                city: 'Perth',
                capacity: 65,
                gameIds: []
            },
            {
                id: 20,
                venue: 'Campbelltown Sports Stadium',
                state: 'NSW',
                city: 'Sydney',
                capacity: 18,
                gameIds: []
            },
            {
                id: 21,
                venue: 'TIO Stadium',
                state: 'NT',
                city: 'Darwin',
                capacity: 13,
                gameIds: []
            },
            {
                id: 22,
                venue: 'Sky Stadium',
                state: 'NZ',
                city: 'Wellington',
                capacity: 35,
                gameIds: []
            },
            {
                id: 23,
                venue: 'One NZ Stadium',
                state: 'NZ',
                city: 'Christchurch',
                capacity: 30,
                gameIds: []
            },
            {
                id: 24,
                venue: 'Glen Willow Oval',
                state: 'NSW',
                city: 'Mudgee',
                capacity: 10,
                gameIds: []
            },
            {
                id: 25,
                venue: 'HBF Park',
                state: 'WA',
                city: 'Perth',
                capacity: 21,
                gameIds: []
            }
        ],
    games: [
        { homeTeam: { localName: 'Melbourne', teamName: 'Storm' },
            awayTeam: { localName: 'Parramatta', teamName: 'Eels' },
            round: 1,
            stadiumId: 2,
            date: '5 March',
            time: '8:00 pm' },
        { homeTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            awayTeam: { localName: 'Sydney', teamName: 'Roosters' },
            round: 1,
            stadiumId: 3,
            date: '6 March',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            awayTeam: { localName: 'Penrith', teamName: 'Panthers' },
            round: 1,
            stadiumId: 1,
            date: '6 March',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            awayTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            round: 1,
            stadiumId: 4,
            date: '7 March',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            awayTeam: { localName: 'Canberra', teamName: 'Raiders' },
            round: 1,
            stadiumId: 5,
            date: '7 March',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            awayTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            round: 1,
            stadiumId: 1,
            date: '8 March',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            awayTeam: { localName: 'Parramatta', teamName: 'Eels' },
            round: 2,
            stadiumId: 1,
            date: '12 March',
            time: '8:00 pm' },
        { homeTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            awayTeam: { localName: 'Canberra', teamName: 'Raiders' },
            round: 2,
            stadiumId: 3,
            date: '13 March',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Sydney', teamName: 'Roosters' },
            awayTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            round: 2,
            stadiumId: 6,
            date: '13 March',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Wests', teamName: 'Tigers' },
            awayTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            round: 2,
            stadiumId: 7,
            date: '14 March',
            time: '3:00 pm' },
        { homeTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            awayTeam: { localName: 'Melbourne', teamName: 'Storm' },
            round: 2,
            stadiumId: 8,
            date: '14 March',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Penrith', teamName: 'Panthers' },
            awayTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            round: 2,
            stadiumId: 9,
            date: '14 March',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            awayTeam: { localName: 'Newcastle', teamName: 'Knights' },
            round: 2,
            stadiumId: 5,
            date: '15 March',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            awayTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            round: 2,
            stadiumId: 1,
            date: '15 March',
            time: '6:15 pm' },
        { homeTeam: { localName: 'Canberra', teamName: 'Raiders' },
            awayTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            round: 3,
            stadiumId: 10,
            date: '19 March',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Sydney', teamName: 'Roosters' },
            awayTeam: { localName: 'Penrith', teamName: 'Panthers' },
            round: 3,
            stadiumId: 6,
            date: '20 March',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Melbourne', teamName: 'Storm' },
            awayTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            round: 3,
            stadiumId: 2,
            date: '20 March',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Newcastle', teamName: 'Knights' },
            awayTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            round: 3,
            stadiumId: 11,
            date: '21 March',
            time: '3:00 pm' },
        { homeTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            awayTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            round: 3,
            stadiumId: 4,
            date: '21 March',
            time: '5:30 pm' },
        { homeTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            awayTeam: { localName: 'Wests', teamName: 'Tigers' },
            round: 3,
            stadiumId: 12,
            date: '21 March',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Parramatta', teamName: 'Eels' },
            awayTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            round: 3,
            stadiumId: 13,
            date: '22 March',
            time: '4:05 pm' },
        { homeTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            awayTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            round: 3,
            stadiumId: 14,
            date: '22 March',
            time: '6:15 pm' },
        { homeTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            awayTeam: { localName: 'Sydney', teamName: 'Roosters' },
            round: 4,
            stadiumId: 5,
            date: '26 March',
            time: '8:00 pm' },
        { homeTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            awayTeam: { localName: 'Wests', teamName: 'Tigers' },
            round: 4,
            stadiumId: 3,
            date: '27 March',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            awayTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            round: 4,
            stadiumId: 1,
            date: '27 March',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            awayTeam: { localName: 'Newcastle', teamName: 'Knights' },
            round: 4,
            stadiumId: 15,
            date: '28 March',
            time: '3:00 pm' },
        { homeTeam: { localName: 'Penrith', teamName: 'Panthers' },
            awayTeam: { localName: 'Parramatta', teamName: 'Eels' },
            round: 4,
            stadiumId: 13,
            date: '28 March',
            time: '5:30 pm' },
        { homeTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            awayTeam: { localName: 'Melbourne', teamName: 'Storm' },
            round: 4,
            stadiumId: 14,
            date: '28 March',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Canberra', teamName: 'Raiders' },
            awayTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            round: 4,
            stadiumId: 10,
            date: '29 March',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            awayTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            round: 4,
            stadiumId: 16,
            date: '29 March',
            time: '6:15 pm' },
        { homeTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            awayTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            round: 5,
            stadiumId: 17,
            date: '2 April',
            time: '8:00 pm' },
        { homeTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            awayTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            round: 5,
            stadiumId: 15,
            date: '3 April',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Penrith', teamName: 'Panthers' },
            awayTeam: { localName: 'Melbourne', teamName: 'Storm' },
            round: 5,
            stadiumId: 13,
            date: '3 April',
            time: '8:00 pm' },
        { homeTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            awayTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            round: 5,
            stadiumId: 18,
            date: '4 April',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            awayTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            round: 5,
            stadiumId: 16,
            date: '4 April',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            awayTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            round: 5,
            stadiumId: 4,
            date: '5 April',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Newcastle', teamName: 'Knights' },
            awayTeam: { localName: 'Canberra', teamName: 'Raiders' },
            round: 5,
            stadiumId: 11,
            date: '5 April',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Parramatta', teamName: 'Eels' },
            awayTeam: { localName: 'Wests', teamName: 'Tigers' },
            round: 5,
            stadiumId: 13,
            date: '6 April',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            awayTeam: { localName: 'Penrith', teamName: 'Panthers' },
            round: 6,
            stadiumId: 15,
            date: '9 April',
            time: '7:50 pm' },
        { homeTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            awayTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            round: 6,
            stadiumId: 8,
            date: '10 April',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            awayTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            round: 6,
            stadiumId: 1,
            date: '10 April',
            time: '8:00 pm' },
        { homeTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            awayTeam: { localName: 'Canberra', teamName: 'Raiders' },
            round: 6,
            stadiumId: 19,
            date: '11 April',
            time: '3:00 pm' },
        { homeTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            awayTeam: { localName: 'Sydney', teamName: 'Roosters' },
            round: 6,
            stadiumId: 19,
            date: '11 April',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Melbourne', teamName: 'Storm' },
            awayTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            round: 6,
            stadiumId: 2,
            date: '11 April',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Parramatta', teamName: 'Eels' },
            awayTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            round: 6,
            stadiumId: 13,
            date: '12 April',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Wests', teamName: 'Tigers' },
            awayTeam: { localName: 'Newcastle', teamName: 'Knights' },
            round: 6,
            stadiumId: 20,
            date: '12 April',
            time: '4:05 pm' },
        { homeTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            awayTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            round: 7,
            stadiumId: 14,
            date: '16 April',
            time: '7:50 pm' },
        { homeTeam: { localName: 'Canberra', teamName: 'Raiders' },
            awayTeam: { localName: 'Melbourne', teamName: 'Storm' },
            round: 7,
            stadiumId: 10,
            date: '17 April',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            awayTeam: { localName: 'Penrith', teamName: 'Panthers' },
            round: 7,
            stadiumId: 21,
            date: '17 April',
            time: '8:00 pm' },
        { homeTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            awayTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            round: 7,
            stadiumId: 3,
            date: '18 April',
            time: '3:00 pm' },
        { homeTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            awayTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            round: 7,
            stadiumId: 15,
            date: '18 April',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Wests', teamName: 'Tigers' },
            awayTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            round: 7,
            stadiumId: 20,
            date: '18 April',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Sydney', teamName: 'Roosters' },
            awayTeam: { localName: 'Newcastle', teamName: 'Knights' },
            round: 7,
            stadiumId: 6,
            date: '19 April',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Parramatta', teamName: 'Eels' },
            awayTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            round: 7,
            stadiumId: 13,
            date: '19 April',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Wests', teamName: 'Tigers' },
            awayTeam: { localName: 'Canberra', teamName: 'Raiders' },
            round: 8,
            stadiumId: 7,
            date: '23 April',
            time: '7:50 pm' },
        { homeTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            awayTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            round: 8,
            stadiumId: 14,
            date: '24 April',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            awayTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            round: 8,
            stadiumId: 1,
            date: '24 April',
            time: '8:00 pm' },
        { homeTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            awayTeam: { localName: 'Sydney', teamName: 'Roosters' },
            round: 8,
            stadiumId: 6,
            date: '25 April',
            time: '4:00 pm' },
        { homeTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            awayTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            round: 8,
            stadiumId: 22,
            date: '25 April',
            time: '6:05 pm' },
        { homeTeam: { localName: 'Melbourne', teamName: 'Storm' },
            awayTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            round: 8,
            stadiumId: 2,
            date: '25 April',
            time: '8:10 pm' },
        { homeTeam: { localName: 'Newcastle', teamName: 'Knights' },
            awayTeam: { localName: 'Penrith', teamName: 'Panthers' },
            round: 8,
            stadiumId: 11,
            date: '26 April',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            awayTeam: { localName: 'Parramatta', teamName: 'Eels' },
            round: 8,
            stadiumId: 5,
            date: '26 April',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            awayTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            round: 9,
            stadiumId: 15,
            date: '1 May',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            awayTeam: { localName: 'Melbourne', teamName: 'Storm' },
            round: 9,
            stadiumId: 1,
            date: '1 May',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            awayTeam: { localName: 'Canberra', teamName: 'Raiders' },
            round: 9,
            stadiumId: 16,
            date: '2 May',
            time: '3:00 pm' },
        { homeTeam: { localName: 'Parramatta', teamName: 'Eels' },
            awayTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            round: 9,
            stadiumId: 13,
            date: '2 May',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Sydney', teamName: 'Roosters' },
            awayTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            round: 9,
            stadiumId: 6,
            date: '2 May',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Newcastle', teamName: 'Knights' },
            awayTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            round: 9,
            stadiumId: 11,
            date: '3 May',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            awayTeam: { localName: 'Wests', teamName: 'Tigers' },
            round: 9,
            stadiumId: 4,
            date: '3 May',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Penrith', teamName: 'Panthers' },
            awayTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            round: 9,
            stadiumId: 13,
            date: '3 May',
            time: '6:15 pm' },
        { homeTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            awayTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            round: 10,
            stadiumId: 1,
            date: '7 May',
            time: '7:50 pm' },
        { homeTeam: { localName: 'Sydney', teamName: 'Roosters' },
            awayTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            round: 10,
            stadiumId: 12,
            date: '8 May',
            time: '6:00 pm' },
        { homeTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            awayTeam: { localName: 'Parramatta', teamName: 'Eels' },
            round: 10,
            stadiumId: 14,
            date: '8 May',
            time: '8:00 pm' },
        { homeTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            awayTeam: { localName: 'Newcastle', teamName: 'Knights' },
            round: 10,
            stadiumId: 8,
            date: '9 May',
            time: '3:00 pm' },
        { homeTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            awayTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            round: 10,
            stadiumId: 15,
            date: '9 May',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            awayTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            round: 10,
            stadiumId: 5,
            date: '9 May',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Melbourne', teamName: 'Storm' },
            awayTeam: { localName: 'Wests', teamName: 'Tigers' },
            round: 10,
            stadiumId: 2,
            date: '10 May',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Canberra', teamName: 'Raiders' },
            awayTeam: { localName: 'Penrith', teamName: 'Panthers' },
            round: 10,
            stadiumId: 10,
            date: '10 May',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            awayTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            round: 11,
            stadiumId: 1,
            date: '15 May',
            time: '6:00 pm' },
        { homeTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            awayTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            round: 11,
            stadiumId: 1,
            date: '15 May',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Wests', teamName: 'Tigers' },
            awayTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            round: 11,
            stadiumId: 1,
            date: '16 May',
            time: '3:00 pm' },
        { homeTeam: { localName: 'Sydney', teamName: 'Roosters' },
            awayTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            round: 11,
            stadiumId: 1,
            date: '16 May',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Parramatta', teamName: 'Eels' },
            awayTeam: { localName: 'Melbourne', teamName: 'Storm' },
            round: 11,
            stadiumId: 1,
            date: '16 May',
            time: '7:45 pm' },
        { homeTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            awayTeam: { localName: 'Newcastle', teamName: 'Knights' },
            round: 11,
            stadiumId: 1,
            date: '17 May',
            time: '2:00 pm' },
        { homeTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            awayTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            round: 11,
            stadiumId: 1,
            date: '17 May',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Penrith', teamName: 'Panthers' },
            awayTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            round: 11,
            stadiumId: 1,
            date: '17 May',
            time: '6:25 pm' },
        { homeTeam: { localName: 'Canberra', teamName: 'Raiders' },
            awayTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            round: 12,
            stadiumId: 10,
            date: '21 May',
            time: '7:50 pm' },
        { homeTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            awayTeam: { localName: 'Melbourne', teamName: 'Storm' },
            round: 12,
            stadiumId: 15,
            date: '22 May',
            time: '8:00 pm' },
        { homeTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            awayTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            round: 12,
            stadiumId: 18,
            date: '23 May',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            awayTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            round: 12,
            stadiumId: 5,
            date: '23 May',
            time: '7:30 pm' },
        { homeTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            awayTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            round: 12,
            stadiumId: 14,
            date: '24 May',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            awayTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            round: 13,
            stadiumId: 4,
            date: '29 May',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Newcastle', teamName: 'Knights' },
            awayTeam: { localName: 'Parramatta', teamName: 'Eels' },
            round: 13,
            stadiumId: 11,
            date: '30 May',
            time: '3:00 pm' },
        { homeTeam: { localName: 'Wests', teamName: 'Tigers' },
            awayTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            round: 13,
            stadiumId: 13,
            date: '30 May',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Melbourne', teamName: 'Storm' },
            awayTeam: { localName: 'Sydney', teamName: 'Roosters' },
            round: 13,
            stadiumId: 2,
            date: '30 May',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            awayTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            round: 13,
            stadiumId: 1,
            date: '31 May',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Canberra', teamName: 'Raiders' },
            awayTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            round: 13,
            stadiumId: 10,
            date: '31 May',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Penrith', teamName: 'Panthers' },
            awayTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            round: 13,
            stadiumId: 13,
            date: '31 May',
            time: '6:15 pm' },
        { homeTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            awayTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            round: 14,
            stadiumId: 5,
            date: '4 June',
            time: '7:50 pm' },
        { homeTeam: { localName: 'Melbourne', teamName: 'Storm' },
            awayTeam: { localName: 'Newcastle', teamName: 'Knights' },
            round: 14,
            stadiumId: 2,
            date: '5 June',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Canberra', teamName: 'Raiders' },
            awayTeam: { localName: 'Sydney', teamName: 'Roosters' },
            round: 14,
            stadiumId: 10,
            date: '5 June',
            time: '8:00 pm' },
        { homeTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            awayTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            round: 14,
            stadiumId: 14,
            date: '6 June',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            awayTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            round: 14,
            stadiumId: 1,
            date: '6 June',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Wests', teamName: 'Tigers' },
            awayTeam: { localName: 'Penrith', teamName: 'Panthers' },
            round: 14,
            stadiumId: 13,
            date: '7 June',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            awayTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            round: 14,
            stadiumId: 4,
            date: '7 June',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            awayTeam: { localName: 'Parramatta', teamName: 'Eels' },
            round: 14,
            stadiumId: 15,
            date: '8 June',
            time: '4:00 pm' },
        { homeTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            awayTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            round: 15,
            stadiumId: 15,
            date: '11 June',
            time: '7:50 pm' },
        { homeTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            awayTeam: { localName: 'Sydney', teamName: 'Roosters' },
            round: 15,
            stadiumId: 1,
            date: '12 June',
            time: '8:00 pm' },
        { homeTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            awayTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            round: 15,
            stadiumId: 3,
            date: '13 June',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Parramatta', teamName: 'Eels' },
            awayTeam: { localName: 'Canberra', teamName: 'Raiders' },
            round: 15,
            stadiumId: 13,
            date: '13 June',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Wests', teamName: 'Tigers' },
            awayTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            round: 15,
            stadiumId: 7,
            date: '14 June',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Newcastle', teamName: 'Knights' },
            awayTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            round: 16,
            stadiumId: 11,
            date: '19 June',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Wests', teamName: 'Tigers' },
            awayTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            round: 16,
            stadiumId: 20,
            date: '20 June',
            time: '3:00 pm' },
        { homeTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            awayTeam: { localName: 'Penrith', teamName: 'Panthers' },
            round: 16,
            stadiumId: 16,
            date: '20 June',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            awayTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            round: 16,
            stadiumId: 15,
            date: '20 June',
            time: '7:30 pm' },
        { homeTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            awayTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            round: 16,
            stadiumId: 23,
            date: '21 June',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Melbourne', teamName: 'Storm' },
            awayTeam: { localName: 'Canberra', teamName: 'Raiders' },
            round: 16,
            stadiumId: 2,
            date: '21 June',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Sydney', teamName: 'Roosters' },
            awayTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            round: 16,
            stadiumId: 6,
            date: '21 June',
            time: '6:15 pm' },
        { homeTeam: { localName: 'Parramatta', teamName: 'Eels' },
            awayTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            round: 17,
            stadiumId: 13,
            date: '25 June',
            time: '7:50 pm' },
        { homeTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            awayTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            round: 17,
            stadiumId: 16,
            date: '26 June',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            awayTeam: { localName: 'Sydney', teamName: 'Roosters' },
            round: 17,
            stadiumId: 1,
            date: '26 June',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            awayTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            round: 17,
            stadiumId: 1,
            date: '27 June',
            time: '3:00 pm' },
        { homeTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            awayTeam: { localName: 'Penrith', teamName: 'Panthers' },
            round: 17,
            stadiumId: 14,
            date: '27 June',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            awayTeam: { localName: 'Melbourne', teamName: 'Storm' },
            round: 17,
            stadiumId: 5,
            date: '27 June',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Canberra', teamName: 'Raiders' },
            awayTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            round: 17,
            stadiumId: 10,
            date: '28 June',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Newcastle', teamName: 'Knights' },
            awayTeam: { localName: 'Wests', teamName: 'Tigers' },
            round: 17,
            stadiumId: 11,
            date: '28 June',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Penrith', teamName: 'Panthers' },
            awayTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            round: 18,
            stadiumId: 13,
            date: '3 July',
            time: '8:00 pm' },
        { homeTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            awayTeam: { localName: 'Wests', teamName: 'Tigers' },
            round: 18,
            stadiumId: 18,
            date: '4 July',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            awayTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            round: 18,
            stadiumId: 1,
            date: '4 July',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Parramatta', teamName: 'Eels' },
            awayTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            round: 18,
            stadiumId: 13,
            date: '5 July',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Newcastle', teamName: 'Knights' },
            awayTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            round: 18,
            stadiumId: 11,
            date: '5 July',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Wests', teamName: 'Tigers' },
            awayTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            round: 19,
            stadiumId: 20,
            date: '10 July',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            awayTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            round: 19,
            stadiumId: 17,
            date: '11 July',
            time: '3:00 pm' },
        { homeTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            awayTeam: { localName: 'Canberra', teamName: 'Raiders' },
            round: 19,
            stadiumId: 15,
            date: '11 July',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Sydney', teamName: 'Roosters' },
            awayTeam: { localName: 'Parramatta', teamName: 'Eels' },
            round: 19,
            stadiumId: 6,
            date: '11 July',
            time: '7:30 pm' },
        { homeTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            awayTeam: { localName: 'Newcastle', teamName: 'Knights' },
            round: 19,
            stadiumId: 15,
            date: '12 July',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            awayTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            round: 19,
            stadiumId: 5,
            date: '12 July',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Melbourne', teamName: 'Storm' },
            awayTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            round: 19,
            stadiumId: 2,
            date: '12 July',
            time: '6:15 pm' },
        { homeTeam: { localName: 'Penrith', teamName: 'Panthers' },
            awayTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            round: 20,
            stadiumId: 13,
            date: '16 July',
            time: '7:50 pm' },
        { homeTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            awayTeam: { localName: 'Newcastle', teamName: 'Knights' },
            round: 20,
            stadiumId: 4,
            date: '17 July',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Sydney', teamName: 'Roosters' },
            awayTeam: { localName: 'Melbourne', teamName: 'Storm' },
            round: 20,
            stadiumId: 6,
            date: '17 July',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Canberra', teamName: 'Raiders' },
            awayTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            round: 20,
            stadiumId: 10,
            date: '18 July',
            time: '3:00 pm' },
        { homeTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            awayTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            round: 20,
            stadiumId: 3,
            date: '18 July',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            awayTeam: { localName: 'Wests', teamName: 'Tigers' },
            round: 20,
            stadiumId: 15,
            date: '18 July',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            awayTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            round: 20,
            stadiumId: 16,
            date: '19 July',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            awayTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            round: 20,
            stadiumId: 1,
            date: '19 July',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Parramatta', teamName: 'Eels' },
            awayTeam: { localName: 'Penrith', teamName: 'Panthers' },
            round: 21,
            stadiumId: 13,
            date: '23 July',
            time: '7:50 pm' },
        { homeTeam: { localName: 'Newcastle', teamName: 'Knights' },
            awayTeam: { localName: 'Sydney', teamName: 'Roosters' },
            round: 21,
            stadiumId: 11,
            date: '24 July',
            time: '6:00 pm' },
        { homeTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            awayTeam: { localName: 'Melbourne', teamName: 'Storm' },
            round: 21,
            stadiumId: 15,
            date: '24 July',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Canberra', teamName: 'Raiders' },
            awayTeam: { localName: 'Wests', teamName: 'Tigers' },
            round: 21,
            stadiumId: 10,
            date: '25 July',
            time: '3:00 pm' },
        { homeTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            awayTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            round: 21,
            stadiumId: 15,
            date: '25 July',
            time: '5:30 pm' },
        { homeTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            awayTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            round: 21,
            stadiumId: 14,
            date: '25 July',
            time: '7:30 pm' },
        { homeTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            awayTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            round: 21,
            stadiumId: 18,
            date: '26 July',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            awayTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            round: 21,
            stadiumId: 5,
            date: '26 July',
            time: '4:05 pm' },
        { homeTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            awayTeam: { localName: 'Sydney', teamName: 'Roosters' },
            round: 22,
            stadiumId: 14,
            date: '30 July',
            time: '7:50 pm' },
        { homeTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            awayTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            round: 22,
            stadiumId: 8,
            date: '31 July',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Melbourne', teamName: 'Storm' },
            awayTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            round: 22,
            stadiumId: 2,
            date: '31 July',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            awayTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            round: 22,
            stadiumId: 16,
            date: '1 August',
            time: '3:00 pm' },
        { homeTeam: { localName: 'Penrith', teamName: 'Panthers' },
            awayTeam: { localName: 'Canberra', teamName: 'Raiders' },
            round: 22,
            stadiumId: 24,
            date: '1 August',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            awayTeam: { localName: 'Newcastle', teamName: 'Knights' },
            round: 22,
            stadiumId: 1,
            date: '1 August',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            awayTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            round: 22,
            stadiumId: 4,
            date: '2 August',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Wests', teamName: 'Tigers' },
            awayTeam: { localName: 'Parramatta', teamName: 'Eels' },
            round: 22,
            stadiumId: 13,
            date: '2 August',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            awayTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            round: 23,
            stadiumId: 16,
            date: '6 August',
            time: '7:50 pm' },
        { homeTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            awayTeam: { localName: 'Penrith', teamName: 'Panthers' },
            round: 23,
            stadiumId: 3,
            date: '7 August',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Sydney', teamName: 'Roosters' },
            awayTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            round: 23,
            stadiumId: 6,
            date: '7 August',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Melbourne', teamName: 'Storm' },
            awayTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            round: 23,
            stadiumId: 25,
            date: '8 August',
            time: '3:00 pm' },
        { homeTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            awayTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            round: 23,
            stadiumId: 1,
            date: '8 August',
            time: '5:30 pm' },
        { homeTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            awayTeam: { localName: 'Parramatta', teamName: 'Eels' },
            round: 23,
            stadiumId: 6,
            date: '8 August',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Canberra', teamName: 'Raiders' },
            awayTeam: { localName: 'Newcastle', teamName: 'Knights' },
            round: 23,
            stadiumId: 10,
            date: '9 August',
            time: '2:00 pm' },
        { homeTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            awayTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            round: 23,
            stadiumId: 18,
            date: '9 August',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Penrith', teamName: 'Panthers' },
            awayTeam: { localName: 'Sydney', teamName: 'Roosters' },
            round: 24,
            stadiumId: 13,
            date: '13 August',
            time: '7:50 pm' },
        { homeTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            awayTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            round: 24,
            stadiumId: 5,
            date: '14 August',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            awayTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            round: 24,
            stadiumId: 15,
            date: '14 August',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            awayTeam: { localName: 'Canberra', teamName: 'Raiders' },
            round: 24,
            stadiumId: 4,
            date: '15 August',
            time: '3:00 pm' },
        { homeTeam: { localName: 'Parramatta', teamName: 'Eels' },
            awayTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            round: 24,
            stadiumId: 13,
            date: '15 August',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            awayTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            round: 24,
            stadiumId: 1,
            date: '15 August',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Newcastle', teamName: 'Knights' },
            awayTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            round: 24,
            stadiumId: 11,
            date: '16 August',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Wests', teamName: 'Tigers' },
            awayTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            round: 24,
            stadiumId: 13,
            date: '16 August',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Melbourne', teamName: 'Storm' },
            awayTeam: { localName: 'Penrith', teamName: 'Panthers' },
            round: 25,
            stadiumId: 2,
            date: '20 August',
            time: '7:50 pm' },
        { homeTeam: { localName: 'Canberra', teamName: 'Raiders' },
            awayTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            round: 25,
            stadiumId: 10,
            date: '21 August',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            awayTeam: { localName: 'Parramatta', teamName: 'Eels' },
            round: 25,
            stadiumId: 1,
            date: '21 August',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Newcastle', teamName: 'Knights' },
            awayTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            round: 25,
            stadiumId: 11,
            date: '22 August',
            time: '3:00 pm' },
        { homeTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            awayTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            round: 25,
            stadiumId: 15,
            date: '22 August',
            time: '5:30 pm' },
        { homeTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            awayTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            round: 25,
            stadiumId: 6,
            date: '22 August',
            time: '7:30 pm' },
        { homeTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            awayTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            round: 25,
            stadiumId: 16,
            date: '23 August',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Sydney', teamName: 'Roosters' },
            awayTeam: { localName: 'Wests', teamName: 'Tigers' },
            round: 25,
            stadiumId: 6,
            date: '23 August',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            awayTeam: { localName: 'Melbourne', teamName: 'Storm' },
            round: 26,
            stadiumId: 1,
            date: '27 August',
            time: '7:50 pm' },
        { homeTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            awayTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            round: 26,
            stadiumId: 5,
            date: '28 August',
            time: '6:00 pm' },
        { homeTeam: { localName: 'Penrith', teamName: 'Panthers' },
            awayTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            round: 26,
            stadiumId: 13,
            date: '28 August',
            time: '8:00 pm' },
        { homeTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            awayTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            round: 26,
            stadiumId: 16,
            date: '29 August',
            time: '3:00 pm' },
        { homeTeam: { localName: 'Sydney', teamName: 'Roosters' },
            awayTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            round: 26,
            stadiumId: 6,
            date: '29 August',
            time: '5:30 pm' },
        { homeTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            awayTeam: { localName: 'Wests', teamName: 'Tigers' },
            round: 26,
            stadiumId: 14,
            date: '29 August',
            time: '7:30 pm' },
        { homeTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            awayTeam: { localName: 'Newcastle', teamName: 'Knights' },
            round: 26,
            stadiumId: 3,
            date: '30 August',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Parramatta', teamName: 'Eels' },
            awayTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            round: 26,
            stadiumId: 13,
            date: '30 August',
            time: '4:05 pm' },
        { homeTeam: { localName: 'Canterbury Bankstown', teamName: 'Bulldogs' },
            awayTeam: { localName: 'Brisbane', teamName: 'Broncos' },
            round: 27,
            stadiumId: 15,
            date: '3 September',
            time: '7:50 pm' },
        { homeTeam: { localName: 'Gold Coast', teamName: 'Titans' },
            awayTeam: { localName: 'Redcliffe', teamName: 'Dolphins' },
            round: 27,
            stadiumId: 16,
            date: '4 September',
            time: '6:00 pm' },
        { homeTeam: { localName: 'South Sydney', teamName: 'Rabbitohs' },
            awayTeam: { localName: 'Sydney', teamName: 'Roosters' },
            round: 27,
            stadiumId: 6,
            date: '4 September',
            time: '8:00 pm' },
        { homeTeam: { localName: 'New Zealand', teamName: 'Warriors' },
            awayTeam: { localName: 'Manly Warringah', teamName: 'Sea Eagles' },
            round: 27,
            stadiumId: 3,
            date: '5 September',
            time: '3:00 pm' },
        { homeTeam: { localName: 'North Queensland', teamName: 'Cowboys' },
            awayTeam: { localName: 'Canberra', teamName: 'Raiders' },
            round: 27,
            stadiumId: 14,
            date: '5 September',
            time: '5:30 pm' },
        { homeTeam: { localName: 'Cronulla', teamName: 'Sharks' },
            awayTeam: { localName: 'Melbourne', teamName: 'Storm' },
            round: 27,
            stadiumId: 4,
            date: '5 September',
            time: '7:30 pm' },
        { homeTeam: { localName: 'St George Illawarra', teamName: 'Dragons' },
            awayTeam: { localName: 'Parramatta', teamName: 'Eels' },
            round: 27,
            stadiumId: 8,
            date: '6 September',
            time: '2:00 pm' },
        { homeTeam: { localName: 'Penrith', teamName: 'Panthers' },
            awayTeam: { localName: 'Wests', teamName: 'Tigers' },
            round: 27,
            stadiumId: 13,
            date: '6 September',
            time: '4:05 pm' }
    ]
}
